# spring configuration
spring:
  application:
    name: os-wombat-backend
  datasource:
    url: jdbc:mysql://localhost:3306/SpringSecurityDB
    username: root
    password: Sqysb0118.
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  security:
    user:
      name: dummyUser
      password: dummyPassword


# MyBatis configuration
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
